import setuptools
from graphgenerator.version import __version__

# https://www.freecodecamp.org/news/build-your-first-python-package/

exec(open("graphgenerator/version.py").read())

setuptools.setup(
    name="social-networks-graph-generator",
    description="CLI tool to generate a graph from a hashtag or expression",
    version=__version__,
    author="Ambanum",
    url="https://github.com/ambanum/social-networks-graph-generator",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
    packages=["graphgenerator"],
    setup_requires=["setuptools_scm"],
    use_scm_version=False,
    include_package_data=True,
    install_requires=[
        "setuptools-scm==6.3.2",
        "networkx==2.6.3",
        "pandas==1.2.5",
        "click==8.0.1",
        "pytz==2021.3",
        "matplotlib==3.5.0",
        "python-louvain==0.15",
        "social-networks-bot-finder==1.2.2",
        "snscrape==0.4.3.20220106",
        "beautifulsoup4==4.10.0",
        "certifi==2021.10.8",
        "charset-normalizer==2.0.11",
        "cloudpickle==2.0.0",
        "cycler==0.11.0",
        "filelock==3.4.2",
        "fonttools==4.29.1",
        "idna==3.3",
        "joblib==1.0.1",
        "kiwisolver==1.3.2",
        "llvmlite==0.38.0",
        "lxml==4.7.1",
        "numba==0.55.1",
        "packaging==21.3",
        "Pillow==9.0.1",
        "pyparsing==3.0.7",
        "PySocks==1.7.1",
        "python-dateutil==2.8.2",
        "requests==2.27.1",
        "scipy==1.8.0",
        "shap==0.39.0",
        "six==1.16.0",
        "slicer==0.0.7",
        "soupsieve==2.3.1",
        "threadpoolctl==3.1.0",
        "tomli==2.0.1",
        "tqdm==4.62.3",
        "urllib3==1.26.8",
        "scikit-learn==0.24.2",
        "numpy==1.21.5",
    ],
    dependency_links=["git+https://github.com/JustAnotherArchivist/snscrape.git"],
    python_requires="~=3.8",
    extras_require={
        "test": ["coverage"],
    },
    entry_points={
        "console_scripts": [
            "graphgenerator=graphgenerator.cli:main",
        ],
    },
)
