edge_source = "source"
edge_target = "target"
edge_date = "dates"
edge_tweet_id = "tweet_id"
edge_url_quoted = "quoted"
edge_url_RT = "retweets"
edge_url_label = "label"
edge_size = "size"
edge_type = "type"
edge_metadata = "metadata"
edge_id = "id"
edge_source_date = "source_date"
edge_weight = "weight"

node_id = "id"
node_label = "label"
node_url_quoted = "quoted"
node_url_RT = "retweets"
node_url_tweet = "tweets"
node_date = "dates"
node_tweet_id = "tweet_id"
node_type_tweet = "from"
node_rt_count = "retweetCount"
node_pos_x = "x"
node_pos_y = "y"
node_pos_z = "z"
node_metadata = "metadata"
node_size = "size"
node_source_date = "source_date"
nodes_community = "community_id"
node_edge_date = "dates_edges"
node_botscore = "botscore"

metadata_search = "search"
metadata_since = "since"
metadata_type_search = "type_search"
metadata_maxresults = "maxresults"
metadata_minretweets = "minretweets"
metadata_last_collected_tweet = "last_collected_tweet"
metadata_last_collected_date = "last_collected_date"
metadata_data_collection_date = "data_collection_date"
metadata_most_recent_tweet = "most_recent_tweet"
metadata_execution_time = "execution_time"
metadata_layout_algo = "layout_algo"
metadata_community_algo = "community_algo"
metadata_n_collected_tweets = "n_collected_tweets"
metadata_n_analysed_tweets = "n_analyzed_tweets"
metadata_status = "status"

col_mapping_type_tweet = {
    node_url_tweet: "original",
    node_url_quoted: "has quoted",
    node_url_RT: "has RT",
}
